### ISSUE TITLE
Error in calibration program

### ISSUE THREAD

**Issue by xiaobai-1-1** [Livox-SDK/Livox_automatic_calibration#2]
After the mapping program,  when the calibration program  read the Target lidar data. There is an error: 

terminate called after throwing an instance of 'std::length of error'
what()   vector::reserve
![2020-07-06 12-10-12屏幕截图](https://user-images.githubusercontent.com/66578141/86588579-8c7e4b80-bfbe-11ea-8b82-042db58777b0.png)

**Comment by DimShuai** [comment]
I have met the same problem, so did you solve it?

**Comment by xiaobai-1-1** [comment]
not yet

**Comment by Livox-SDK** [comment]
Hi, xiaobai-1-1
Thanks for your feedback!
What is your OS version? Our code test environment is ubuntu16.04

**Comment by xiaobai-1-1** [comment]
yes, my version is also ubuntu16.04.

**Comment by Livox-SDK** [comment]
Thank you for sharing this issue, but we can't reproduce this error, we suggest you use gdb to debug it. Hope you can find this bug and we can fix it as soon as possible!

**Comment by LeisureLei** [comment]
just comment the line "viewer_final->spinOnce(10)"

**Comment by Rogeerrr** [comment]
> just comment the line "viewer_final->spinOnce(10)"

3q very much
