### ISSUE TITLE
fitline process not use ransac algorithm to fit a line

### ISSUE THREAD

**Issue by yumingdong** [Livox-SDK/Livox_automatic_calibration#5]
In this source code repository, ransac program only read ../data/calib_data.txt ,and only extract the last line of (x,y,z,roll,pitch,yaw) as the final result, but didn't use ransac algorithm.

**Comment by Chrislzy1993** [comment]
我在看源代码也看到了这个

**Comment by ZYXiao-g** [comment]
我认为不用ransac是有道理的,它这个的原理是 x-1 * a * x = b， 标定参数是不断进行迭代优化的。理论上说最后一次精度是最高的，但这样的结果容易受到误差影响。

**Comment by Livox-SDK** [comment]
Hi yumingdong  Chrislzy1993 ZYXiao-g,
我们放了这个接口在代码里,但是实际上真正调用的还是均值法
