### ISSUE TITLE
some compile errors for PCL 1.8 in windows platform.

### ISSUE THREAD

**Issue by liang0724s** [Livox-SDK/Livox_automatic_calibration#6]
1>------ 已启动生成: 项目: calibration, 配置: Debug Win32 ------
1>calibration.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/point_traits.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>D:\PCL\PCL 1.8.1\3rdParty\Boost\include\boost-1_64\boost/iostreams/positioning.hpp(96): warning C4996: 'std::fpos<_Mbstatet>::seekpos': warning STL4019: The member std::fpos::seekpos() is non-Standard, and is preserved only for compatibility with workarounds for old versions of Visual C++. It will be removed in a future release, and in this release always returns 0. Please use standards-conforming mechanisms to manipulate fpos, such as conversions to and from streamoff, or an integral type, instead. If you are receiving this message while compiling Boost.IOStreams, a fix has been submitted upstream to make Boost use standards-conforming mechanisms, as it does for other compilers. You can define _SILENCE_FPOS_SEEKPOS_DEPRECATION_WARNING to acknowledge that you have received this warning, or define _REMOVE_FPOS_SEEKPOS to remove std::fpos::seekpos entirely.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\iosfwd(59): note: 参见“std::fpos<_Mbstatet>::seekpos”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/io/pcd_io.h(281): warning C4003: 类函数宏的调用“max”参数不足
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/io/pcd_io.h(281): error C2589: “(”:“::”右边的非法标记
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/io/pcd_io.h(281): error C2059: 语法错误:“)”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/io/impl/pcd_io.hpp(107): warning C4003: 类函数宏的调用“max”参数不足
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/io/impl/pcd_io.hpp(119): warning C4003: 类函数宏的调用“max”参数不足
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/correspondence.h(75): warning C4003: 类函数宏的调用“max”参数不足
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/correspondence.h(75): error C2589: “(”:“::”右边的非法标记
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/correspondence.h(75): error C2062: 意外的类型“unknown-type”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/correspondence.h(75): error C2612: 基/成员初始值设定项列表中的非法后缀“)”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/cloud_iterator.h(61): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/cloud_iterator.h(115): note: 参见对正在编译的 类 模板 实例化 "pcl::pcl::CloudIterator<PointT>" 的引用
1>D:\PCL\PCL 1.8.1\3rdParty\Boost\include\boost-1_64\boost/bind/placeholders.hpp(54): note: 参见对正在编译的 类 模板 实例化 "boost::arg<9>" 的引用
1>D:\PCL\PCL 1.8.1\3rdParty\Boost\include\boost-1_64\boost/bind/placeholders.hpp(53): note: 参见对正在编译的 类 模板 实例化 "boost::arg<8>" 的引用
1>D:\PCL\PCL 1.8.1\3rdParty\Boost\include\boost-1_64\boost/bind/placeholders.hpp(52): note: 参见对正在编译的 类 模板 实例化 "boost::arg<7>" 的引用
1>D:\PCL\PCL 1.8.1\3rdParty\Boost\include\boost-1_64\boost/bind/placeholders.hpp(51): note: 参见对正在编译的 类 模板 实例化 "boost::arg<6>" 的引用
1>D:\PCL\PCL 1.8.1\3rdParty\Boost\include\boost-1_64\boost/bind/placeholders.hpp(50): note: 参见对正在编译的 类 模板 实例化 "boost::arg<5>" 的引用
1>D:\PCL\PCL 1.8.1\3rdParty\Boost\include\boost-1_64\boost/bind/placeholders.hpp(49): note: 参见对正在编译的 类 模板 实例化 "boost::arg<4>" 的引用
1>D:\PCL\PCL 1.8.1\3rdParty\Boost\include\boost-1_64\boost/bind/placeholders.hpp(48): note: 参见对正在编译的 类 模板 实例化 "boost::arg<3>" 的引用
1>D:\PCL\PCL 1.8.1\3rdParty\Boost\include\boost-1_64\boost/bind/placeholders.hpp(47): note: 参见对正在编译的 类 模板 实例化 "boost::arg<2>" 的引用
1>D:\PCL\PCL 1.8.1\3rdParty\Boost\include\boost-1_64\boost/bind/placeholders.hpp(46): note: 参见对正在编译的 类 模板 实例化 "boost::arg<1>" 的引用
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/cloud_iterator.h(61): error C2143: 语法错误: 缺少“,”(在“&”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/cloud_iterator.h(130): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/cloud_iterator.h(187): note: 参见对正在编译的 类 模板 实例化 "pcl::pcl::ConstCloudIterator<PointT>" 的引用
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/cloud_iterator.h(130): error C2143: 语法错误: 缺少“,”(在“&”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/impl/cloud_iterator.hpp(355): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/impl/cloud_iterator.hpp(355): error C2988: 不可识别的模板声明/定义
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/impl/cloud_iterator.hpp(355): error C2143: 语法错误: 缺少“,”(在“&”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/impl/cloud_iterator.hpp(469): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/impl/cloud_iterator.hpp(469): error C2988: 不可识别的模板声明/定义
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/impl/cloud_iterator.hpp(469): error C2143: 语法错误: 缺少“,”(在“&”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(91): error C2039: “PointCloud”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(91): error C2988: 不可识别的模板声明/定义
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(91): error C2143: 语法错误: 缺少“)”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(91): error C2143: 语法错误: 缺少“;”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(91): error C2059: 语法错误:“<”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(92): error C2065: “Scalar”: 未声明的标识符
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(92): error C2923: “Eigen::Matrix”: 对于参数“_Scalar”，“Scalar”不是有效的 模板 类型变量
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(92): error C2059: 语法错误:“)”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(95): error C2039: “PointCloud”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(95): error C2988: 不可识别的模板声明/定义
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(95): error C2143: 语法错误: 缺少“)”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(95): error C2143: 语法错误: 缺少“;”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(95): error C2059: 语法错误:“<”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(96): error C2059: 语法错误:“)”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(97): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(97): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(102): error C2039: “PointCloud”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(102): error C2988: 不可识别的模板声明/定义
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(102): error C2143: 语法错误: 缺少“)”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(102): error C2143: 语法错误: 缺少“;”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(102): error C2059: 语法错误:“<”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(103): error C2059: 语法错误:“)”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(104): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(104): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(119): error C2039: “PointCloud”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(119): error C2988: 不可识别的模板声明/定义
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(119): error C2143: 语法错误: 缺少“)”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(119): error C2143: 语法错误: 缺少“;”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(119): error C2059: 语法错误:“<”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(121): error C2065: “Scalar”: 未声明的标识符
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(121): error C2923: “Eigen::Matrix”: 对于参数“_Scalar”，“Scalar”不是有效的 模板 类型变量
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(121): error C2059: 语法错误:“)”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(124): error C2039: “PointCloud”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(124): error C2988: 不可识别的模板声明/定义
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(124): error C2143: 语法错误: 缺少“)”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(124): error C2143: 语法错误: 缺少“;”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(124): error C2059: 语法错误:“<”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(126): error C2059: 语法错误:“)”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(127): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(127): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(132): error C2039: “PointCloud”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(132): error C2988: 不可识别的模板声明/定义
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(132): error C2143: 语法错误: 缺少“)”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(132): error C2143: 语法错误: 缺少“;”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(132): error C2059: 语法错误:“<”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(134): error C2059: 语法错误:“)”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(135): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(135): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(150): error C2039: “PointCloud”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(150): error C2988: 不可识别的模板声明/定义
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(150): error C2143: 语法错误: 缺少“)”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(150): error C2143: 语法错误: 缺少“;”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(150): error C2059: 语法错误:“<”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(151): error C2039: “PointIndices”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(152): error C2065: “Scalar”: 未声明的标识符
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(152): error C2923: “Eigen::Matrix”: 对于参数“_Scalar”，“Scalar”不是有效的 模板 类型变量
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(152): error C2059: 语法错误:“)”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(155): error C2039: “PointCloud”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(155): error C2988: 不可识别的模板声明/定义
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(155): error C2143: 语法错误: 缺少“)”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(155): error C2143: 语法错误: 缺少“;”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(155): error C2059: 语法错误:“<”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(156): error C2039: “PointIndices”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(157): error C2059: 语法错误:“)”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(158): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(158): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(163): error C2039: “PointCloud”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(163): error C2988: 不可识别的模板声明/定义
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(163): error C2143: 语法错误: 缺少“)”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(163): error C2143: 语法错误: 缺少“;”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(163): error C2059: 语法错误:“<”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(164): error C2039: “PointIndices”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(165): error C2059: 语法错误:“)”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(166): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(166): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(184): error C2039: “PointCloud”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(184): error C2988: 不可识别的模板声明/定义
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(184): error C2143: 语法错误: 缺少“)”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(184): error C2143: 语法错误: 缺少“;”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(184): error C2059: 语法错误:“<”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(185): error C2065: “Scalar”: 未声明的标识符
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(185): error C2923: “Eigen::Matrix”: 对于参数“_Scalar”，“Scalar”不是有效的 模板 类型变量
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(186): error C2065: “Scalar”: 未声明的标识符
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(186): error C2923: “Eigen::Matrix”: 对于参数“_Scalar”，“Scalar”不是有效的 模板 类型变量
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(186): error C2059: 语法错误:“)”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(189): error C2039: “PointCloud”: 不是“pcl::pcl”的成员
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(54): note: 参见“pcl::pcl”的声明
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(189): error C2988: 不可识别的模板声明/定义
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(189): error C2143: 语法错误: 缺少“)”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(189): error C2143: 语法错误: 缺少“;”(在“<”的前面)
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(189): error C2059: 语法错误:“<”
1>D:\PCL\PCL 1.8.1\include\pcl-1.8\pcl/common/centroid.h(189): fatal error C1003: 错误计数超过 100；正在停止编译

**Comment by Livox-SDK** [comment]
Hi liang0724s,
基于您的报错信息 我目前推测 可能你的目录有中文名称
